# Generated by Django 4.2.5 on 2023-09-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='number',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='hars1234', max_length=16),
        ),
    ]
