# Generated by Django 4.2.5 on 2023-09-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userdetails_name_alter_userdetails_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='merchant_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.customer_details')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.merchant_details')),
                ('order_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_locations', to='members.customer_details')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='merchant_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_available', models.IntegerField()),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.merchant_details')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.product_details')),
            ],
        ),
    ]
